// Generates opencode-web-ui.gen.ts from packages/app/dist
import { join, relative } from "path"
import { Glob } from "bun"

const distDir = join(import.meta.dir, "../app/dist")
const outFile = join(import.meta.dir, "opencode-web-ui.gen.ts")

const files = await Array.fromAsync(new Glob("**/*").scan({ cwd: distDir, onlyFiles: true }))
const map: Record<string, string> = {}
for (const f of files) {
  const absPath = join(distDir, f).replaceAll("\\", "/")
  map[f] = absPath
}

const src = `// Auto-generated by gen-web-ui.ts — DO NOT EDIT
export default ${JSON.stringify(map, null, 2)} as Record<string, string>
`
await Bun.write(outFile, src)
console.log(`Generated opencode-web-ui.gen.ts with ${files.length} files`)
